Flaky tests in AbstractSimulatedMesosSchedulerDriverTest and JobRetryTest classes
In `JobRetryTest` all tests used the same application name/job group info which somtimes caused
job create errors:

`
com.netflix.titus.master.integration.v3.job.JobRetryTest > testServiceJobFailsAfterRetrying FAILED
    java.lang.RuntimeException: GRPC status Status{code=INVALID_ARGUMENT, description=JobManagerException: Constraint violation - job with group sequence v3App-main-GA-v000 exists (7e4d6e5b-1522-4021-81b9-542df881cfe6), cause=null}: JobManagerException: Constraint violation - job with group sequence v3App-main-GA-v000 exists (7e4d6e5b-1522-4021-81b9-542df881cfe6)
`

`AbstractSimulatedMesosSchedulerDriverTest` incorrectly handled offers in the `testTaskKill` test.